language: python

python:
  - "3.5"
  - "3.6"

# TODO: remove these overrides once default dist supports python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - "pip install astroid==2.0.0 flake8 pylint pytest isort yapf requests kafka-python aiohttp avro-python3 aiosocksy"

script:
  - "make pylint"
  - "make flake8"
  - "make unittest"
